version: '3'
services:  
  database-mysql:
      image: mysql:5.6
      ports:
          - 3307:3306
      environment: 
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=useraccess
          - MYSQL_USER=root
          - MYSQL_PASSWORD=1234
      networks:
          - my_network

  user-access:
      build:
        context: .
        dockerfile: Dockerfile
      image: useraccess:latest
      ports: 
          - 8081:8080
      environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://database-mysql:3306/useraccess?useSSL=false
      depends_on: 
          - database-mysql
      networks:
          - my_network
      links:
          - database-mysql
      
networks:
    my_network:
      driver: bridge